import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'The August Home',
  description: 'Generated by create next app'
}

export default function Home() {
  return <div>Hello, World</div>
}
